### ISSUE TITLE
Attribute Error while Executing the script

### ISSUE THREAD

**Issue by Vishnu-C** [ulrich1a/sheet_ufo#1]
Steps performed

1. Workbench selected as Part
2. Macro -> Macros
3. Loaded the .py file

![image](https://user-images.githubusercontent.com/10018119/43813250-7f62b0ce-9ae2-11e8-8572-0fa969faa94f.png)

4. Imported a step file
5. Selected a Face by clicking on it with left mouse button

![image](https://user-images.githubusercontent.com/10018119/43813375-1121862a-9ae3-11e8-9a42-2d7c6df1d06e.png)

6. Again Macro->Macros
7. Selected the loaded macro and clicked Execute

Report view outputs the below error

> Traceback (most recent call last):
>   File "E:/projects/current/ssab_project/project_files/sheet_ufo-master/sheet_ufo.py", line 1808, in <module>
>     theUnfold, foldLines, nVec, shapeName = getUnfold()
>   File "E:/projects/current/ssab_project/project_files/sheet_ufo-master/sheet_ufo.py", line 1745, in getUnfold
>     TheTree = SheetTree(o.Object.Shape, f_number) # initializes the tree-structure
>   File "E:/projects/current/ssab_project/project_files/sheet_ufo-master/sheet_ufo.py", line 350, in __init__
>     if (self.__thickness < estimated_thickness) or (self.__thickness > 1.9 * estimated_thickness):
> <type 'exceptions.AttributeError'>: 'SheetTree' object has no attribute '_SheetTree__thickness'

**Comment by ulrich1a** [comment]
I made a couple of updates to the script. Can you test with the new version again?
I am interested in files for testing. Can you upload your step file?

**Comment by Vishnu-C** [comment]
Thanks!
I tested again, it works perfect now!

Added the .stp file I used for testing.
[planar_part.zip](https://github.com/ulrich1a/sheet_ufo/files/2300464/planar_part.zip)

**Comment by ulrich1a** [comment]
Thank you for providing the step-file.
Closing the issue as solved.
